_wandb:
    value:
        cli_version: 0.24.0
        e:
            cqy55iy27qxorl6boxpdjn34ckq2re7l:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                args:
                    - model.name=simple
                    - lr=5e-4
                    - epochs=2
                    - batch_size=64
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "199214374912"
                email: s245465@dtu.dk
                executable: /Users/jonathan/Desktop/MLOPS/mlops_project/.venv/bin/python3
                git:
                    commit: e20a27fd6b5e78e34f3ed3a564a8a7ee1cbf7b1b
                    remote: https://github.com/Colmeray/mlops_project
                host: MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: -m project.train
                python: CPython 3.13.7
                root: /Users/jonathan/Desktop/MLOPS/mlops_project
                startedAt: "2026-01-17T12:56:39.785792Z"
                writerId: cqy55iy27qxorl6boxpdjn34ckq2re7l
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 16
                - 61
            "4": 3.13.7
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 2
lr:
    value: 0.0005
model:
    value:
        freeze_features: true
        name: simple
seed:
    value: 42
val_frac:
    value: 0.1
